name: flutter_svg_pro
description: "An interactive, highly-optimized, isolate-powered SVG parsing and rendering engine for Flutter with CSS styling and selection hit-testing."
version: 1.0.1
homepage: https://github.com/khsuzan/flutter_svg_pro
repository: https://github.com/khsuzan/flutter_svg_pro

environment:
  sdk: ^3.11.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  xml: ">=6.5.0 <8.0.0"
  path_drawing: ^1.0.1
  vector_math: ">=2.1.0 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
